### ISSUE TITLE
signrawtransaction bug when wallet is encrypted

### ISSUE THREAD

**Issue by emeth-** [Peerunity/Peerunity#153]
If a wallet is encrypted, the signrawtransaction call will throw a "wallet must be unlocked first" error regardless of whether the wallet is locked or unlocked.

**Comment by brossi** [comment]
Thank you for submitting this, @emeth- 

@sigmike or @glv2 - If either of you have time, could you please review this PR for a second (or third) set of eyes? This is the Peerunity version of the [PR that @emeth- submitted to Peercoin core for branch 0.4.1](https://github.com/ppcoin/ppcoin/pull/83).

Thank you!

**Comment by glv2** [comment]
I took a look at the PR #154 and it looks good.
