### ISSUE TITLE
Suggestion: Use a different icon color for minting transactions that haven't reached 520 verifications

### ISSUE THREAD

**Issue by Thireus** [Peerunity/Peerunity#173]
When a minting transactions hasn't reached 520 block (coins still on hold), the transaction icon in the transactions tab should be different (i.e. little ✓ icon, but orange instead for example). So that users can easily spot which transactions correspond to their coins that are on hold.

![capture d ecran 2015-05-09 a 06 30 46](https://cloud.githubusercontent.com/assets/721759/7548871/fa698b7e-f614-11e4-9eb3-e0a1636f80fa.png) --> Please, make it orange for unconfirmed minting transactions :)

**Comment by glv2** [comment]
The commit ccb4ae46909f3de6b018c82941537461bb74e3f5 changed this and now the clock icons are used for immature minting transactions (like for unconfirmed regular transactions, but the green tick icon only appears after 520 blocks).

I think it was included in v0.1.2-rc2.

**Comment by Thireus** [comment]
Ah, thank you glv2!
