### ISSUE TITLE
"clock icon“ of new POS block transaction not updated correctly

### ISSUE THREAD

**Issue by mh001** [Peerunity/Peerunity#175]
In the transaction pane of the wallet, a new transaction has a clock icon in front. It changes colors and 1/6's as confirmations come. The clock becomes a green tick after 6 confirmation. In the latest peerunity the clock will take several days to turn green. Restarting the wallet doesn't help.

**Comment by glv2** [comment]
The clock for regular transactions becomes a green tick after 6 confirmations.

The clock for newly minted blocks takes 3.5 days to become a green tick because it takes 520 confirmations for minted coins to become spendable.
(c.f. issue #173)

**Comment by mh001** [comment]
Thanks glv!

**Comment by mh001** [comment]
Thanks glv!
