### ISSUE TITLE
listminting RPC feature enhancement

### ISSUE THREAD

**Issue by BlueMeanie** [Peerunity/Peerunity#37]
create a new RPC call 'listminting', explained here by @brossi : http://www.peercointalk.org/index.php?topic=2635.0

**Comment by meonkeys** [comment]
Note: that link above to `peercointalk.org` [doesn't work](https://talk.peercoin.net/t/odd-redirect-for-www-peercointalk-org-dns-hijack/16799).

I think the correct forum link is https://talk.peercoin.net/t/enhancement-request-method-to-retrieve-list-of-mature-transactions-w-details/2190
